import Head from 'next/head';
import { Inter } from 'next/font/google';
import ProductCard from '@/components/ProductCard';
import Navbar from '@/components/Navbar';
import Hero from '@/components/Hero';
import Footer from '@/components/Footer';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="sm:container sm:mx-auto">
          <Navbar className="bg-full-dark" />
          <Hero className="" />
          <ProductCard
            image="/1.jpg"
            title="Nutella Pie"
            calories={216}
            price={9.0}
          />
          <Footer className="" />
        </div>
      </main>
    </>
  );
}
